name: Bug report
description: Report a reproducible bug
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough detail to reproduce the issue.
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, install method
      placeholder: "macOS 14, Python 3.13, pip install -r requirements.txt"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      render: shell
